apiVersion: apps/v1
kind: Deployment
metadata:
  name: loademulator-deployment
spec:
  selector:
    matchLabels:
      app: loademulator
  replicas: 1
  template:
    metadata:
      labels:
        app: loademulator
    spec:
      containers:
      - name: loademulator
        image: load-emulator:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
            httpHeaders:
            - name: Custom-Header
              value: Alive
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
            httpHeaders:
            - name: Custom-Header
              value: Ready
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

